### ISSUE TITLE
Cannot read property 'getCurrentPosition' of undefined

### ISSUE THREAD

**Issue by mdshadman** [jonoj-team/capacitor-fused-location#4]
I am getting this error 
Cannot read property 'getCurrentPosition' of undefined
Please help me, how to solve this error

**Comment by johannesnormannjensen** [comment]
What platform are you trying this on?

**Comment by mdshadman** [comment]
I am using this on Ionic React with capacitor

**Comment by johannesnormannjensen** [comment]
Okay, are you on iOS, Android or Web?

**Comment by mdshadman** [comment]
Android

**Comment by bacques** [comment]
We also had the issue after updating the plugin. In our case the problem was, that the name of the plugin changed from "FusedLocationPlugin" to "FusedLocation", therefore js didn't find the appropriate method to call.
So try rename the call from "Plugins.FusedLocationPlugin.getCurrentPosition()" to "Plugins.FusedLocation.getCurrentPosition()"
Hope this helps.

**Comment by johannesnormannjensen** [comment]
@jonoj/capacitor-fused-location is abandoned as a project since Capacitor uses FusedLocationProvider as default on android.

Anyone using this plugin should revert to using the default Capacitor geolocation implementation.
